### PR TITLE
Fix update and error event skip issue

### LINKED ISSUE #339: [BUG] Error events are getting ignored after dynamic client change
**Describe the bug**
BotKube skips error events event is the error events are configured in resource config

**To Reproduce**
- Deploy BotKube with pod error events
- Create a Pod with invalid image

**Expected behavior**
BotKube should report error event

**Screenshots**

### PR DESCRIPTION
**Pull request by PrasadG193**
##### ISSUE TYPE
 - Feature Pull Request

##### SUMMARY

- Fix Allowed maps checks
- Update diff calculation logic

Fixes #339 #342

### CODE REVIEW

File: pkg/controller/controller.go [hunk 1]
```diff
@@ -188,17 +191,26 @@ func sendEvent(obj, oldObj interface{}, c *config.Config, notifiers []notify.Not
...
+		updateSetting, exist := utils.AllowedUpdateEventsMap[utils.KindNS{Resource: resource, Namespace: "all"}]
 		if !exist {
 			// Check if specified namespace is allowed
-			updateSetting, exist = utils.AllowedUpdateEventsMap[utils.KindNS{Resource: kind, Namespace: objectMeta.Namespace}]
+			updateSetting, exist = utils.AllowedUpdateEventsMap[utils.KindNS{Resource: resource, Namespace: objectMeta.Namespace}]
 		}
 		if exist {
-			updateMsg = utils.Diff(oldObj, obj, updateSetting)
+			// Calculate object diff as per the updateSettings
+			var x, y *unstructured.Unstructured
```
Comment (sanketsudake) [inline pkg/controller/controller.go:205]: Can you please give proper variable names according to usage ?

Comment (PrasadG193) [reply pkg/controller/controller.go]: Done!

**Review by sanketsudake — APPROVED** [review]
