### PR TITLE
Fixed namespace checker to use the correct name

### LINKED ISSUE #419: [BUG] Ignored namespace list gets ignored
Since updating from 0.10.0 to 0.11.0, ignoring some namespaces while including "all" doesn't work--the ignore list seems to simply be ignored:

```
config:
  ## Resources you want to watch
  resources:
  - name: v1/pods
    namespaces:
      include:
        - all
      ignore:
        - test
    events:
      - all
    updateSetting:
      includeDiff: true
      fields:
        - spec.template.spec.containers[*].image
        - status.availableReplicas

  # Check true if you want to receive recommendations
  # about the best practices for the created resource
  recommendations: true

  # Cluster Setting to manage command execution access
  settings:
    # Set true to enable kubectl commands execution
    allowkubectl: false

    # Set true to enable commands execution from configured channel only
    restrictAccess: false

    # Set true to enable config watcher
    configwatcher: true

    # Set false to disable upgrade notification
    upgradeNotifier: true
```

Specifying certain namespaces to include does work, but isn't ideal

### PR DESCRIPTION
**Pull request by hellozee**
##### ISSUE TYPE
 - Bug fix Pull Request

##### SUMMARY
Apparently the wrong member was used to check the resource name. I don't
know how resillient this patch is, but it works for most of the part.

Fixes #419

### CODE REVIEW

File: pkg/filterengine/filters/namespace_checker.go [hunk 1]
```diff
@@ -56,7 +56,8 @@ func (f NamespaceChecker) Run(object interface{}, event *events.Event) {
 	}
 	if botkubeConfig != nil {
 		for _, resource := range botkubeConfig.Resources {
-			if resource.Name == strings.ToLower(event.Kind) {
+			resourceName := strings.Split(strings.ToLower(event.Title), " ")[0]
+			if resource.Name == resourceName {
```
Comment (PrasadG193) [inline pkg/filterengine/filters/namespace_checker.go:60]: @hellozee we have a helper function implemented which returns GVR from given Kind https://github.com/infracloudio/botkube/blob/develop/pkg/utils/utils.go#L258. We can use that method to build "group/version/resource" or "version/resource" (if the group is nil) check

**Review by PrasadG193 — CHANGES_REQUESTED** [review]

File: pkg/filterengine/filters/namespace_checker.go (hunk 1 above)
Comment (hellozee) [reply pkg/filterengine/filters/namespace_checker.go:60]: This is not working for delete events since the resource type return by that method is `/`. Here is how I am trying to do it.
```go
var eventObj *coreV1.Event
err := utils.TransformIntoTypedObject(object.(*unstructured.Unstructured), &eventObj)
if err != nil {
    log.Errorf("Unable to transform object type: %v, into type: %v", reflect.TypeOf(object), reflect.TypeOf(eventObj))
    return
}
tempResourceName, _ := utils.GetResourceFromKind(eventObj.InvolvedObject.GroupVersionKind())
resourceName := utils.GVRToString(tempResourceName)
```

Comment (PrasadG193) [reply pkg/filterengine/filters/namespace_checker.go:60]: @hellozee let's do this
1. Add a new field `Resource` in the Event struct
2. Set the Resource value while creating New Event
3. Refer event.Resource while building Title as well as in filters
Sounds good?

Comment (hellozee) [reply pkg/filterengine/filters/namespace_checker.go:60]: Cool, will do that instead, 🐱

Comment (billimek) [reply pkg/filterengine/filters/namespace_checker.go:60]: @hellozee will you be able to implement the suggested changes?

Comment (hellozee) [reply pkg/filterengine/filters/namespace_checker.go:60]: Ahh sorry, completely forgot about it, will do by this weekend, 😸

Comment (PrasadG193) [reply pkg/filterengine/filters/namespace_checker.go:60]: Hey @hellozee, please let me know if you are working on this.

Comment (hellozee) [reply pkg/filterengine/filters/namespace_checker.go:60]: whoops! expect a PR by evening for sure, 🙃

**Comment by hellozee** [comment]
Done, but this doesn't work in case of a delete event.

**Comment by PrasadG193** [comment]
@hellozee do you mind adding the e2e test for the namespace checker filter (https://github.com/infracloudio/botkube/blob/develop/test/e2e/filters/filters.go#L44)? I am fine if we address that as a separate task.
Please file an issue if you can't add that in this PR.
Thank you!

**Review by PrasadG193 — APPROVED** [review]

**Comment by hellozee** [comment]
It would be better if someone else picks it. I cant promise anything this week, sorry. If no one picks it up this week, I would put up a patch next week, 🐱

**Comment by PrasadG193** [comment]
Sounds good @hellozee

**Comment by PrasadG193** [comment]
Filed https://github.com/infracloudio/botkube/issues/443 to track. Merging this PR

**Comment by PrasadG193** [comment]
@hellozee this doesn't seem to be working. I've added a fix https://github.com/infracloudio/botkube/pull/449. PTAL
